version: '3.9'

services:
  db:
    image: postgres:14
    container_name: social_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: social_automation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: social_media_redis_cache
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: social_media_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env  # Reference .env file
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
